[package]
name = "osrs-ge-calc"
version = "0.4.1"
edition = "2024"
authors = ["N3cro0oDev"]
build = "build.rs"

[build-dependencies]
winresource = "0.1.0"

[dependencies]
iced = { version = "0.14.0", features = ["canvas", "smol", "image"] }
reqwest = { version = "0.13", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.149"
serde-xml-rs = "0.8.2"
num-format = "0.4.4"
webbrowser = "1.1.0"
dirs = "6.0.0"
plotters-iced2 = "0.14"
plotters = "0.3.7"
chrono = "0.4.44"
open = "5"
regex = "1.12.3"
rodio = "0.22.2"
rand = "0.10.0"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62.2", features = ["Win32_UI_Shell", "Win32_System_Com", "Win32_Foundation"]}
